[package]
name = "wyrmas_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
dot-writer = "0.1.4"
rand = "0.8.5"
sdl2 = { version = "0.37.0", features = ["gfx"] }
